const PROVERBS = [
  "A still cup sees farther than a busy one.",
  "The second steep tells the truth the first one only hinted at.",
  "Hot water, cool mind.",
  "Even a cracked gaiwan can teach patience.",
  "Do not chase the aroma. Let it sit down first.",
  "The leaf has already done the hard work. You are only pouring.",
  "Three infusions in, the tea remembers who picked it.",
  "Bitter then sweet is not a flaw. It is the plot.",
  "A watched steep still finishes. An unwatched one does too.",
  "Empty the cup so the next one has somewhere to go.",
  "Old trees are not in a hurry. Neither is this water.",
  "If the lid smells of orchard, you are not late.",
  "The best rinse is the one you actually do.",
  "A loud pour does not make a louder tea.",
  "Steam is just the kettle gossiping.",
  "Drink the tea you have, not the cake you meant to buy.",
  "The wet leaf is the receipt.",
  "Soft water, stubborn rock oolong. They work it out.",
  "One more steep is a philosophy, not a recipe.",
  "If you can name every note, you are talking more than tasting.",
  "The gaiwan does not care about your schedule.",
  "Patience is cheaper than another gram.",
  "A quiet table makes a louder huigan.",
  "Leave some liquor in the cup. The tea likes company.",
  "Even emperors had to wait for the kettle.",
  "The mountain is in the leaf. You are only visiting.",
  "Rinse the dust, not the character.",
  "Today’s bitterness is tomorrow’s camphor, if you let it rest.",
  "A good guest cake is the one you actually share.",
  "Count infusions. Do not count worries.",
  "The timer is a suggestion. The liquor is the vote.",
  "If it tastes like a wet forest, you have arrived.",
  "Boiling water is a compliment to dark tea, not a threat.",
  "Green tea is a sprinter. Puerh is a novel.",
  "Do not punish a delicate leaf with a rolling boil. It remembers.",
  "The third steep is where the vendor’s story either holds or folds.",
  "A lid forgotten is still a lid. A steep forgotten is a soup.",
  "Your caddy is not a museum unless you never open it.",
  "The best tasting note is the one you write after swallowing.",
  "If the cup is too hot to hold, the leaf is just getting started.",
  "A silly proverb still steeps. This one, for instance.",
  "Confucius never timed a flash steep, but he would have approved of the rinse.",
  "The kettle sings because it cannot taste. That is your job.",
  "Even Laozi would have checked the timer. Probably.",
  "This infusion is shorter than a dynastic cycle. You can wait.",
  "A wooden fish keeps time in a temple. You have a phone. Same idea.",
  "If the tea is smoky, blame the roast, not last night’s barbecue. Usually.",
  "The leaf does not know it is Tuesday.",
  "Pour like you mean it, then sit like you do not.",
  "A full mouth is a better critic than a full sentence.",
];

export function proverbFor(seed: string, infusion: number): string {
  if (PROVERBS.length === 0) return "";
  let h = infusion * 2654435761;
  for (let i = 0; i < seed.length; i++) h = (h + seed.charCodeAt(i) * (i + 3)) >>> 0;
  return PROVERBS[h % PROVERBS.length] ?? PROVERBS[0];
}
